In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
# Define the image as a 2D NumPy array
image = np.array([
    [0,   0,   1, 102, 102],
    [0,   0,   2, 104, 104],
    [0,   0,   3, 106, 106],
    [0,   0,   4, 108, 108]
], dtype=float)

print("Original Image:")
print(image)


Original Image:
[[  0.   0.   1. 102. 102.]
 [  0.   0.   2. 104. 104.]
 [  0.   0.   3. 106. 106.]
 [  0.   0.   4. 108. 108.]]


In [5]:
# Define Sobel-X and Sobel-Y kernels
sobel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=float)

sobel_y = np.array([
    [1,  2,  1],
    [0,  0,  0],
    [-1, -2, -1]
], dtype=float)

print("\nSobel-X Kernel:")
print(sobel_x)

print("\nSobel-Y Kernel:")
print(sobel_y)
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt



Sobel-X Kernel:
[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]

Sobel-Y Kernel:
[[ 1.  2.  1.]
 [ 0.  0.  0.]
 [-1. -2. -1.]]


In [6]:
# Apply Sobel-X and Sobel-Y kernels to the image
Gx = ndimage.convolve(image, sobel_x)
Gy = ndimage.convolve(image, sobel_y)

print("\nGradient in X direction (Gx):")
print(Gx)

print("\nGradient in Y direction (Gy):")
print(Gy)



Gradient in X direction (Gx):
[[   0.   -5. -410. -405.    0.]
 [   0.   -8. -416. -408.    0.]
 [   0.  -12. -424. -412.    0.]
 [   0.  -15. -430. -415.    0.]]

Gradient in Y direction (Gy):
[[ 0.  1.  4.  7.  8.]
 [ 0.  2.  8. 14. 16.]
 [ 0.  2.  8. 14. 16.]
 [ 0.  1.  4.  7.  8.]]


In [8]:
gradient_magnitude_approx = np.abs(Gx) + np.abs(Gy)
gradient_magnitude_approx

array([[  0.,   6., 414., 412.,   8.],
       [  0.,  10., 424., 422.,  16.],
       [  0.,  14., 432., 426.,  16.],
       [  0.,  16., 434., 422.,   8.]])